title: [Monetary anchoring and inflation - through dynamic multiagent multiperiod computational modelling]
description: [Proposal for a strategy-proof mechanism design at the next Bretton Woods]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-cayman
google_analytics: UA-175064932-3 
